
OBJS = hworld.o instru.o
KMOD = hworld.o

# ccflags-y += -finstrument-functions -g

all:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules
clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean

obj-m           := $(KMOD)
$(KMOD)-objs    := $(OBJS)
