" Originally was using this at Tejas Networks. Fedora 12 2008 - 2011. Modified version ever since
" Be sure to update vim when using this config file. Use, distribute, contribute however you want
" I want to add comments on each line explaining functionality

" ------------- < cscope> -------------------
" autoload_cscope.vim has been moved to .vim/plugin
" ------------- </cscope> -------------------

" execute pathogen#infect()

" Persistent Folding " select and zf to fold
" au BufWinLeave ?* mkview
" au BufWinEnter ?* silent loadview

set colorcolumn=80     " set cc=80
" set fdo-=search

set ruler
set rulerformat=%50(%f\ %5l,%-6(%c%V%)\ %P%)
set backspace=2
set nocompatible
set shiftwidth=4
set ai
set sm
set nu
set ic
set wrap
set linebreak
set wildmode=list:longest
set textwidth=0
set incsearch
set hlsearch
set bg=dark
set cindent
set splitright
set splitbelow
" set paste
set nowrap
" set lines=60 columns=150 " Needed for givm on windows
set guifont=-Misc-Fixed-Medium-R-SemiCondensed--13-120-75-75-C-60-KOI8-R
" set spell spelllang=en_us
syntax on

" restore last cursor position for individual files
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
nnoremap <c-]> g<c-]>
vnoremap <c-]> g<c-]>

" The following is from Aerohive NUUC
" let g:MultipleSearchMaxColors=10
":Search ab
":Search cd
":Search ef
":Search gh
":Search ij
":Search kl
":Search mn
":Search op
":Search qr
":Search st
":Search uv
":Search wx
":Search yz
":Search 01
":Search 23
":Search 45
":Search 67
":Search 89

:nmap <F10> :set invnumber<CR>
